[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "swanepoel"
version = "0.1.0"
dependencies = ["numpy", "scipy", "pandas", "matplotlib"]

[tool.setuptools.packages.find]
where = ["src"]
